# Simplified Email Configuration for Work Planner MCP Server
# Focused on essential functionality only

# Email Provider Configuration
provider:
  type: "gmail_smtp"
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  security: "tls"

# Environment Variables Required:
# EMAIL_USERNAME: Your email address (e.g., pacaramu@redhat.com)
# EMAIL_PASSWORD: App password or SMTP password
# EMAIL_FROM: Sender email address (usually same as EMAIL_USERNAME)

# Recipients Configuration - Simplified to single recipient
recipients:
  email: "pacaramu@redhat.com"

# Email Templates - Simplified with required templates
templates:
  daily_summary:
    subject: "📊 Work Planner Daily Summary - {team} - {date}"
    body_template: |
      <h2>📊 Work Planner Daily Summary</h2>
      
      <p><strong>Team:</strong> {team}</p>
      <p><strong>Date:</strong> {date}</p>
      <p><strong>Generated:</strong> {generated_time}</p>
      
      <h3>📱 Slack Analysis</h3>
      {slack_analysis}
      
      <h3>🎫 Jira Analysis</h3>
      {jira_analysis}
      
      <h3>📋 Summary</h3>
      {email_summary}
      
      <hr>
      <p><em>Generated by Work Planner MCP Server</em></p>
  
  alert:
    subject: "🚨 Work Planner Alert"
    body_template: |
      <h2>🚨 Alert Notification</h2>
      <p>{content}</p>
      <hr>
      <p><em>Generated by Work Planner MCP Server</em></p>
  
  data_collection_report:
    subject: "📋 Data Collection Report"
    body_template: |
      <h2>📋 Data Collection Report</h2>
      <p>Team: {team}</p>
      <p>Date: {date}</p>
      <p>Status: {status}</p>
      <hr>
      <p><em>Generated by Work Planner MCP Server</em></p>