# Work Planner MCP Server Schedule Configuration
# Simplified configuration inspired by jira-report-mpc project

# Global settings
global:
  timezone: "UTC"
  retention_days: 30
  max_age_hours: 24

# Simple daily schedule - runs at 6 AM UTC daily
schedule: "0 6 * * *"

# Teams configuration
teams:
  - name: "toolchain"
    slack_channels: "all"
    jira_filter: "All In Progress"
  - name: "foa"
    slack_channels: "all"
    jira_filter: "All In Progress"
  - name: "assessment"
    slack_channels: "all"
    jira_filter: "All In Progress"
  - name: "boa"
    slack_channels: "all"
    jira_filter: "All In Progress"

# Email configuration
email:
  enabled: true
  template: "team_daily_report"
  send_to_team: true
  include_ai_analysis: true

# Data collection settings
data_collection:
  slack:
    enabled: true
    include_attachments: false
  jira:
    enabled: true
  ai_analysis:
    enabled: true
    provider: "gemini"

# Cleanup settings
cleanup:
  enabled: true
  schedule: "0 2 * * 0"  # Weekly cleanup on Sunday
  retention_days: 30
  keep_latest: 10