# Slack Channel to Team Mapping Configuration
# This file maps Slack channel IDs to team IDs for data collection

slack_channels:
  # ToolChain Team Channels
  "C04JDFLHJN6": "toolchain"  # team-toolchain-automotive
  "C05BYR06B0V": "toolchain"  # toolchain-infra
  "C04U16VAWL9": "toolchain"  # toolchain-release-readiness
  "C095CUUBNM9": "toolchain"  # toolchain-sla
  "C0910QFKTSN": "toolchain"  # toolchain-AI
  "C064MPL86N6": "toolchain"  # toolchain-errata
    
  # FoA Team Channels  
  "C0659G4HAF9": "foa"        # team-auto-follow-on-activities
  
  # Assessment Team Channels
  "C065HHG49QB": "assessment" # team-auto-assessment
  
  # BoA Team Channels
  "C04QNKX7RU4": "boa"        # boa-team
  
  # SP-RHIVOS Team Channels
  "C06B9BCD456": "sp-rhivos"  # SP-RHIVOS team channel

# Data Collection Settings
data_collection:
  # How far back to fetch messages (in days)
  history_days: 30
  
  # Text dump file location (relative to project root)
  dump_directory: "slack_dumps"
  
  # Parsed dump file location (relative to project root)
  parsed_directory: "slack_dumps_parsed"

# Bot Display Names Mapping
# Maps Slack bot IDs to display names for search functionality
# This maps bot IDs to their application names for better readability
bot_display_names:
  "B05NMKVG": "Rhivos-webserver notifier"  # Real bot ID from RHIVOS alerts
  "B06B9BCD456": "SP-RHIVOS notifier"  
  "B1234567891": "Assessment bot"
  # Example: If you see bot ID B02AX123456 in channel, map it like:
  # "B02AX123456": "Auto-deployment-bot"
  # Add more bot mappings as needed

# User Display Names Mapping
# Maps Slack user IDs to display names for search functionality
# This is the single source of truth for all user mappings
user_display_names:
  "UJJV82KRP": "Eli Mesika"
  "U011CBYSALV": "Michal Skrivanek"
  "U01552Z34RG": "Yosi Ben Shimon"
  "U0171SJF00H": "Hubert Stefanski"
  "U018G4EKMSA": "Yariv Rachmani"
  "U01B16R8TNC": "Davide Caratti"
  "U01CA50VC3C": "Daniel Farrell"
  "U01KBN9MFB7": "Jaime Flynn"
  "U01NHRC0E4D": "Miloslav Trmač"
  "U01TKQ3K2HM": "Adam Černý"
  "U01TXCW3RMF": "Ed Chong"
  "U01V2TVUSV6": "Lukas Holecek"
  "U0205F28UMN": "Stephen Smoogen"
  "U020YLADEKA": "Avihai Efrat"
  "U028B6GFVHV": "Matt Currier"
  "U028BN60UGJ": "Andrew Hills"
  "U028G091SNM": "Brian Grech"
  "U02CVB7MDK8": "Maya Peretz"
  "U02DXVBD5CP": "Kanitha Chim"
  "U02E54249V5": "Patricia Viladegut"
  "U02F2L89YTS": "Juanje Ojeda"
  "U02JHD5HMGC": "Robert O'Brien"
  "U02M0G43C2F": "Jiri B-a"
  "U02QFB1R4SE": "Ren Yang"
  "U02SMLD2JTY": "Milos Prchlik"
  "U039S3WUR3Q": "Andreia Gaita"
  "U039U9VMNCC": "Jon Orris"
  "U03BXJ3CYKX": "Amanda Sopkin"
  "U03DQ7V743D": "Christian Kellner"
  "U03DM1LN4UW": "Charles Timko"
  "U03GHUGCJPP": "Gabriel N. de C."
  "U03GVFNAWAC": "JT Tinkham"
  "U03HHMDH8CX": "Rony Gong"
  "U03PXHBRX5Z": "Kartik Shah"
  "U03PV3B9Q7K": "Tomas Golembiovsky"
  "U03Q57JBXK4": "Khaled El-Sayed"
  "U044WFQDKBK": "Shawn Jamison"
  "U04AGK8UJ2V": "Inho Cho"
  "U04AGQD0K8D": "Nisha Saini"
  "U04AXB4GK52": "Ryan Smith"
  "U04CLM07JNA": "Sagar Sundaray"
  "U04FTPUGJH1": "John Dennis"
  "U04HK2W8NGL": "Marcin Sobczyk"
  "U04JCCD2ZB7": "Kudos"
  "U04JCEH31RV": "Alex McLeod"
  "U04JD5EV3MJ": "Julio Faracco"
  "U04JDAPLMSN": "Jochen Breuer"
  "U04JJADSWGM": "Chuang Cao"
  "U04JPFBCSTB": "Francisco da Rocha"
  "U04JRTQ4LHK": "Michael Ho"
  "U04JV0JBEFM": "Jim Bair"
  "U04K6JJJULC": "Miroslav Vadkerti"
  "U04KJ2RSEL8": "Rob"
  "U04KM6EGXC3": "Alberto Martin"
  "U04KLL3QSF4": "Marcel Banas"
  "U04KNU6HGCU": "Petr Matyas"
  "U04L83NL5MK": "David O'Brien"
  "U04LP69FP6X": "Sameera Kalgudi"
  "U04MGT65NQJ": "Eitan Raviv"
  "U04MD42UL92": "Sabine Vogel"
  "U04MTUF83QX": "Pierre-Yves Chibon"
  "U04MUFF92JZ": "Albert Esteve"
  "U04MXBN4WRZ": "Enric Balletbo"
  "U04MXTNUW1Z": "Allison King"
  "U04N0SVB92Q": "Rakesh Musalay"
  "U04N2DV1W3Y": "Rachel Sibley"
  "U04N4GB25GV": "Bilal Elmoussaoui"
  "U04N6RDGNAU": "Alessandro Carminati"
  "U04N98MG9DG": "Fabrizio Tronci"
  "U04N9LTR47M": "Paul Caramuto"
  "U04NH4CEEJF": "Shir Fishbain"
  "U04NHMNPD32": "Eric Chanudet"
  "U04NHTDFS6P": "Steve Loranz"
  "U04NL553V53": "Felicia Kleinfelt"
  "U04NLT3HY3Y": "Simon Walter"
  "U04NSVCMTBP": "Advait Shailesh Gupte"
  "U04NW5PV4DA": "Jilun Li"
  "U04NZ662TAL": "Leonardo Garcia"
  "U04NN2GEXLZ": "Petr Sabata"
  "U04NNGY4QQ2": "Ozan Unsal"
  "U04P10NE5A5": "Iker Galardi"
  "U04PQB5SV41": "Stephen Bertram"
  "U04Q4USRZTM": "Luigi Pellecchia"
  "U04QDJC59E2": "Brendan Donegan"
  "U04QH469ETF": "Austin Kimbrell"
  "U04QL3MD2CB": "Tom Callaway"
  "U04QL2XHGP4": "Dylan Gross"
  "U04QNH25QA1": "Roni Eliezer"
  "U04QUNNNX16": "Philip Daly"
  "U04QYMVRDDF": "Jan Onderka"
  "U05AAM5H2MC": "Pablo Ridolfi"
  "U05AGS4SE78": "Wisdom Omuya"
  "U06J9AHRB37": "Andrea F."
  "U06N09DL50A": "ATC Demo Reminder"
  "U8E7ZSTTQ": "Martin Perina"
  "UDAENJUEB": "Troy Dawson"
  "UDLVC8W83": "Asaf Rachmani"
  "UEFFLKJAJ": "Miguel Angel Ajo Pelayo"
  "UEHF1HH6Y": "Leonardo Rossetti"
  "UFB1TK0Q7": "Lev Veyde"
  "UG0N57XEX": "Pavol Brilla"
  "UG137FY4U": "Dustin Black"
  "UH5H4M38F": "Yaning Wang"
  "UKSDRN92R": "Martin Coufal"
  "UKSAK8JRH": "Shaun Daley"
  "ULXQZ1GUQ": "Lenka Špačková"
  "UN1JC12N4": "Michel Normand"
  "UNMGRQNRZ": "Sandro Bonazzola"
  "URH2PJUCV": "Arik Hadas"
  "UTYJ8SA2G": "Pavol Brilla"  # Assessment team member (from message content)
  "U05ST6V6HDY": "John Smith"  # Assessment team member  
  "U9AA9E30B": "Jane Doe"      # Assessment team member
  "U06SS4RC5H7": "Bob Johnson" # Assessment team member

# Unknown Users - Manual mapping required
# Add real names when discovered, organize by channel and activity date
unknown_users:
  # team-toolchain-automotive (C04JDFLHJN6) - Recent activity
  "U010SFHC919": "User U010SFHC919"  # team-toolchain-automotive - 2 messages - 2024-09-28
  "U013JQ19RB9": "User U013JQ19RB9"  # team-toolchain-automotive - 4 messages - 2024-09-28
  "U013NFL4MN0": "User U013NFL4MN0"  # team-toolchain-automotive - 1 message - 2024-09-28
  "U016DB0CPT8": "User U016DB0CPT8"  # team-toolchain-automotive - 39 messages - 2024-09-28
  "U01AYQUDCDU": "User U01AYQUDCDU"  # team-toolchain-automotive - 2 messages - 2024-09-28
  "U01B5J3607K": "User U01B5J3607K"  # team-toolchain-automotive - 62 messages - 2024-09-28
  "U01TD879DV5": "User U01TD879DV5"  # team-toolchain-automotive - 1 message - 2024-09-28
  "U01V835CCJ3": "User U01V835CCJ3"  # team-toolchain-automotive - 7 messages - 2024-09-28
  "U0208S4QJJW": "User U0208S4QJJW"  # team-toolchain-automotive - 2 messages - 2024-09-28
  "U020F1CM8F6": "User U020F1CM8F6"  # team-toolchain-automotive - 12 messages - 2024-09-28
  "U02831EQBML": "User U02831EQBML"  # team-toolchain-automotive - 70 messages - 2024-09-28
  "U02F97ACPN2": "User U02F97ACPN2"  # team-toolchain-automotive - 2 messages - 2024-09-28
  "U02FYT9UV0A": "User U02FYT9UV0A"  # team-toolchain-automotive - 2 messages - 2024-09-28
  "U02GPUD416E": "User U02GPUD416E"  # team-toolchain-automotive - 2 messages - 2024-09-28
  "U038PS0N6J3": "User U038PS0N6J3"  # team-toolchain-automotive - 12 messages - 2024-09-28
  "U03KTGK0ACB": "User U03KTGK0ACB"  # team-toolchain-automotive - 17 messages - 2024-09-28
  "U03M23HUZN3": "User U03M23HUZN3"  # team-toolchain-automotive - 33 messages - 2024-09-28
  "U03NPDKU3S8": "User U03NPDKU3S8"  # team-toolchain-automotive - 48 messages - 2024-09-28
  "U04885FKWF8": "User U04885FKWF8"  # team-toolchain-automotive - 12 messages - 2024-09-28
  "U049ZDBUUMQ": "User U049ZDBUUMQ"  # team-toolchain-automotive - 34 messages - 2024-09-28
  "U04AGAJFC12": "User U04AGAJFC12"  # team-toolchain-automotive - 1 message - 2024-09-28
  "U04JEVACPPG": "User U04JEVACPPG"  # team-toolchain-automotive - 7 messages - 2024-09-28
  "U04JMECPXLZ": "User U04JMECPXLZ"  # team-toolchain-automotive - 5 messages - 2024-09-28
  "U04KDHZPC2Y": "User U04KDHZPC2Y"  # team-toolchain-automotive - 8 messages - 2024-09-28
  "U04KGBNTDQW": "User U04KGBNTDQW"  # team-toolchain-automotive - 1 message - 2024-09-28
  "U04KRJNH10U": "User U04KRJNH10U"  # team-toolchain-automotive - 2 messages - 2024-09-28
  "U04MSUAS5GX": "User U04MSUAS5GX"  # team-toolchain-automotive - 2 messages - 2024-09-28
  "U04MVNZUJPN": "User U04MVNZUJPN"  # team-toolchain-automotive - 10 messages - 2024-09-28
  "U04MZUSUBNG": "User U04MZUSUBNG"  # team-toolchain-automotive - 2 messages - 2024-09-28
  "U04N6161AQ7": "User U04N6161AQ7"  # team-toolchain-automotive - 3 messages - 2024-09-28
  "U04NBMCBURF": "User U04NBMCBURF"  # team-toolchain-automotive - 1 message - 2024-09-28
  "U04NDGABHHA": "User U04NDGABHHA"  # team-toolchain-automotive - 16 messages - 2024-09-28
  "U04NLPFA9LN": "User U04NLPFA9LN"  # team-toolchain-automotive - 1 message - 2024-09-28
  "U04NNFWH45S": "User U04NNFWH45S"  # team-toolchain-automotive - 89 messages - 2024-09-28
  "U04NNVCQU11": "User U04NNVCQU11"  # team-toolchain-automotive - 1 message - 2024-09-28
  "U04NQRLEGCV": "User U04NQRLEGCV"  # team-toolchain-automotive - 5 messages - 2024-09-28
  "U04NRKQUG69": "User U04NRKQUG69"  # team-toolchain-automotive - 11 messages - 2024-09-28
  "U04NTHZUA4B": "User U04NTHZUA4B"  # team-toolchain-automotive - 7 messages - 2024-09-28
  "U04NV7WG690": "User U04NV7WG690"  # team-toolchain-automotive - 4 messages - 2024-09-28
  "U04NV83KF0S": "User U04NV83KF0S"  # team-toolchain-automotive - 2 messages - 2024-09-28
  "U04NXNHCT28": "User U04NXNHCT28"  # team-toolchain-automotive - 10 messages - 2024-09-28
  "U04P6AQ9V5X": "User U04P6AQ9V5X"  # team-toolchain-automotive - 61 messages - 2024-09-28
  "U04PA360T8Q": "User U04PA360T8Q"  # team-toolchain-automotive - 1 message - 2024-09-28
  "U04Q51Y2K18": "User U04Q51Y2K18"  # team-toolchain-automotive - 19 messages - 2024-09-28
  "U04Q5LSQ0R5": "User U04Q5LSQ0R5"  # team-toolchain-automotive - 79 messages - 2024-09-28
  "U04QAEAG56V": "User U04QAEAG56V"  # team-toolchain-automotive - 81 messages - 2024-09-28
  "U04QDQYQ0SF": "User U04QDQYQ0SF"  # team-toolchain-automotive - 1 message - 2024-09-28
  "U04QNBZUT2R": "User U04QNBZUT2R"  # team-toolchain-automotive - 24 messages - 2024-09-28
  "U04QPB7V40Y": "User U04QPB7V40Y"  # team-toolchain-automotive - 14 messages - 2024-09-28
  "U04RJ3MM4HE": "User U04RJ3MM4HE"  # team-toolchain-automotive - 2 messages - 2024-09-28
  "U04SNH8Q39P": "User U04SNH8Q39P"  # team-toolchain-automotive - 52 messages - 2024-09-28
  "U0567AK1E4R": "User U0567AK1E4R"  # team-toolchain-automotive - 22 messages - 2024-09-28
  "U058GGPL547": "User U058GGPL547"  # team-toolchain-automotive - 5 messages - 2024-09-28
  "U058HASJX40": "User U058HASJX40"  # team-toolchain-automotive - 4 messages - 2024-09-28
  "U05AXEH6Z8D": "User U05AXEH6Z8D"  # team-toolchain-automotive - 3 messages - 2024-09-28
  "U05E3JA63S9": "User U05E3JA63S9"  # team-toolchain-automotive - 27 messages - 2024-09-28
  "U05KXAGUF89": "User U05KXAGUF89"  # team-toolchain-automotive - 32 messages - 2024-09-28
  "U064YNKHH43": "User U064YNKHH43"  # team-toolchain-automotive - 13 messages - 2024-09-28
  "U06C0TN0KMK": "User U06C0TN0KMK"  # team-toolchain-automotive - 6 messages - 2024-09-28
  "U06H27JSYN5": "User U06H27JSYN5"  # team-toolchain-automotive - 6 messages - 2024-09-28
  "U06MVBSDH25": "User U06MVBSDH25"  # team-toolchain-automotive - 1 message - 2024-09-28
  "U06SH0BGH3M": "User U06SH0BGH3M"  # team-toolchain-automotive - 1 message - 2024-09-28
  "U08R77Q5WKX": "User U08R77Q5WKX"  # team-toolchain-automotive - 4 messages - 2024-09-28
  "U098QAXP4D9": "User U098QAXP4D9"  # team-toolchain-automotive - 3 messages - 2024-09-28
  "U09F4MFQF8D": "User U09F4MFQF8D"  # team-toolchain-automotive - 3 messages - 2024-09-28
  "U09F4VDKSCD": "User U09F4VDKSCD"  # team-toolchain-automotive - 3 messages - 2024-09-28
  "U99PQE5FD": "User U99PQE5FD"  # team-toolchain-automotive - 2 messages - 2024-09-28
  "U9AR7FQTA": "User U9AR7FQTA"  # team-toolchain-automotive - 9 messages - 2024-09-28
  "U9C4P0LA2": "User U9C4P0LA2"  # team-toolchain-automotive - 1 message - 2024-09-28
  "UH51FGD3P": "User UH51FGD3P"  # team-toolchain-automotive - 1 message - 2024-09-28
  "UKSDQ0GGY": "User UKSDQ0GGY"  # team-toolchain-automotive - 4 messages - 2024-09-28
  "UMP1VK6FQ": "User UMP1VK6FQ"  # team-toolchain-automotive - 3 messages - 2024-09-28
  "UNX7Y1K4G": "User UNX7Y1K4G"  # team-toolchain-automotive - 8 messages - 2024-09-28
  "USLACKBOT": "User USLACKBOT"  # team-toolchain-automotive - 172 messages - 2024-09-28
  "USRS4HYUS": "User USRS4HYUS"  # team-toolchain-automotive - 27 messages - 2024-09-28
  "UUFS0HRTR": "User UUFS0HRTR"  # team-toolchain-automotive - 2 messages - 2024-09-28