name: Daily Team Report - Jira & Slack Summary

on:
  schedule:
    # Run every day at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  daily-team-report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate Daily Team Report
      env:
        SLACK_XOXC_TOKEN: ${{ secrets.SLACK_XOXC_TOKEN }}
        SLACK_XOXD_TOKEN: ${{ secrets.SLACK_XOXD_TOKEN }}
        JIRA_URL: ${{ secrets.JIRA_URL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_TOKEN }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      run: |
        python -c "
        import os
        import json
        import smtplib
        from email.mime.text import MIMEText
        from email.mime.multipart import MIMEMultipart
        from datetime import datetime
        
        print('🚀 Starting Daily Team Report Generation...')
        
        # Collect and analyze data for each team
        teams = ['toolchain', 'foa', 'assessment', 'boa']
        
        for team in teams:
            print(f'\\n📊 Processing team: {team.upper()}')
            
            # Collect Slack data directly
            slack_summary = 'No Slack data available'
            slack_details = []
            try:
                from connectors.slack.client import SlackClient
                from connectors.slack.config import SlackConfig
                
                slack_config = SlackConfig.load('config/slack.yaml')
                slack_client = SlackClient(slack_config)
                
                # Find team channels
                slack_channels = slack_config.get('slack_channels', {})
                team_channels = [ch_id for ch_id, team_name in slack_channels.items() if team_name == team]
                
                print(f'  📱 Found {len(team_channels)} channels for {team}')
                
                if team_channels:
                    # Get messages directly from Slack API
                    for channel_id in team_channels:
                        try:
                            print(f'  📱 Fetching messages from channel: {channel_id}')
                            messages = slack_client.get_channel_messages(channel_id, limit=50)
                            
                            if messages:
                                slack_summary = f'Slack data collected from {len(team_channels)} channels ({len(messages)} messages)'
                                
                                # Get recent messages for summary
                                recent_messages = messages[-5:] if messages else []
                                for msg in recent_messages:
                                    user = msg.get('user', 'Unknown')
                                    text = msg.get('text', 'No text')
                                    slack_details.append(f'  - {user}: {text[:100]}...')
                                break
                        except Exception as e:
                            print(f'  ⚠️  Slack channel {channel_id}: {e}')
                            continue
                
            except Exception as e:
                print(f'  ❌ Slack collection failed: {e}')
            
            # Collect Jira data directly
            jira_summary = 'No Jira data available'
            jira_details = []
            try:
                from connectors.jira.client import JiraClient
                from connectors.jira.config import JiraConfig
                
                jira_config = JiraConfig.load('config/jira.yaml')
                jira_client = JiraClient(jira_config)
                
                print(f'  🎫 Collecting Jira data for {team}...')
                
                # Build JQL query for team
                team_users = jira_config.get('teams', {}).get(team, {}).get('users', [])
                if team_users:
                    jql_query = f'project = \"{jira_config.get(\"project_key\", \"AFT\")}\" AND assignee in ({", ".join(team_users)}) AND statusCategory in (\"In Progress\", \"New\", \"Closed\") ORDER BY updatedDate DESC'
                else:
                    # Fallback: search by project and status
                    jql_query = f'project = \"{jira_config.get(\"project_key\", \"AFT\")}\" AND statusCategory in (\"In Progress\", \"New\", \"Closed\") ORDER BY updatedDate DESC'
                
                print(f'  🎫 JQL Query: {jql_query}')
                
                # Get issues directly from Jira API
                issues = jira_client.search_issues(jql_query)
                
                if issues:
                    jira_summary = f'{len(issues)} tickets in progress'
                    print(f'  🎫 Found {len(issues)} issues for {team}')
                    
                    # Format ticket details (inspired by jira-report-mpc)
                    for issue in issues[:10]:  # Limit to 10 most recent
                        try:
                            # Handle both dict and object formats
                            if isinstance(issue, dict):
                                key = issue.get('key', 'N/A')
                                fields = issue.get('fields', {})
                                summary = fields.get('summary', 'No summary')
                                status_obj = fields.get('status', {})
                                status = status_obj.get('name', 'Unknown') if isinstance(status_obj, dict) else getattr(status_obj, 'name', 'Unknown')
                                assignee_obj = fields.get('assignee', {})
                                assignee = assignee_obj.get('displayName', 'Unassigned') if isinstance(assignee_obj, dict) else getattr(assignee_obj, 'displayName', 'Unassigned')
                                updated = fields.get('updated', 'Unknown')
                            else:
                                key = getattr(issue, 'key', 'N/A')
                                summary = getattr(issue.fields, 'summary', 'No summary')
                                status = getattr(issue.fields.status, 'name', 'Unknown')
                                assignee = getattr(issue.fields.assignee, 'displayName', 'Unassigned') if issue.fields.assignee else 'Unassigned'
                                updated = getattr(issue.fields, 'updated', 'Unknown')
                            
                            ticket_info = f\"\"\"
        ==========
        Issue: {key}
        ({jira_config.get('jira_url', '')}/browse/{key})
        Owner: {assignee}
        Summary: {summary}
        Status: {status}
        Updated: {updated}
        \"\"\"
                            jira_details.append(ticket_info.strip())
                        except Exception as e:
                            print(f'  ⚠️  Error formatting issue: {e}')
                            continue
                else:
                    print(f'  ⚠️  No Jira issues found for {team}')
                
            except Exception as e:
                print(f'  ❌ Jira collection failed: {e}')
            
            # Generate AI summary if available
            ai_summary = 'AI analysis not available'
            try:
                from connectors.gemini.client import GeminiClient
                from connectors.gemini.config import GeminiConfig
                
                gemini_config = GeminiConfig()
                gemini_client = GeminiClient(gemini_config.get_config())
                
                print(f'  🤖 Generating AI summary for {team}...')
                
                # Create summary of collected data
                summary_text = f\"\"\"
                Team: {team}
                Slack Activity: {slack_summary}
                Jira Tickets: {jira_summary}
                
                Recent Slack Messages:
                {chr(10).join(slack_details) if slack_details else 'No recent messages'}
                
                Jira Issues:
                {chr(10).join(jira_details) if jira_details else 'No issues found'}
                \"\"\"
                
                prompt = f\"\"\"
                Analyze the following team data and provide insights:
                
                {summary_text}
                
                Please provide:
                1. Key themes and patterns
                2. Potential blockers or risks
                3. Productivity suggestions
                4. Team workload distribution
                
                Keep the response concise and actionable.
                \"\"\"
                
                ai_response = gemini_client.generate_content(prompt)
                if ai_response:
                    ai_summary = ai_response
                    print(f'  🤖 AI analysis completed')
                else:
                    print(f'  ⚠️  AI analysis returned empty response')
                
            except Exception as e:
                print(f'  ⚠️  AI analysis failed: {e}')
            
            # Create email content (inspired by jira-report-mpc format)
            email_body = f\"\"\"
        <h2>📊 {team.upper()} Team Daily Report</h2>
        
        <p><strong>Date:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        <p><strong>Team:</strong> {team.upper()}</p>
        
        <h3>📱 Slack Activity</h3>
        <p>{slack_summary}</p>
        {''.join(f'<p>{detail}</p>' for detail in slack_details) if slack_details else ''}
        
        <h3>🎫 Jira Tickets - In Progress</h3>
        <p><strong>{jira_summary}</strong></p>
        
        {''.join(f'<pre>{detail}</pre>' for detail in jira_details) if jira_details else '<p>No tickets found</p>'}
        
        <h3>🤖 AI Analysis</h3>
        <p>{ai_summary}</p>
        
        <hr>
        <p><em>Generated by Work Planner MCP Server</em></p>
        \"\"\"
            
            # Send email
            try:
                email_username = os.getenv('EMAIL_USERNAME')
                email_password = os.getenv('EMAIL_PASSWORD') 
                email_from = os.getenv('EMAIL_FROM')
                
                msg = MIMEMultipart('alternative')
                msg['Subject'] = f'📊 {team.upper()} Team Daily Report - {datetime.now().strftime(\"%Y-%m-%d\")}'
                msg['From'] = email_from
                msg['To'] = email_from
                
                # Add HTML content
                html_part = MIMEText(email_body, 'html')
                msg.attach(html_part)
                
                server = smtplib.SMTP('smtp.gmail.com', 587)
                server.starttls()
                server.login(email_username, email_password)
                server.send_message(msg)
                server.quit()
                
                print(f'  ✅ Daily report email sent for {team.upper()} team!')
                
            except Exception as e:
                print(f'  ❌ Failed to send email for {team}: {e}')
                continue
        
        print('\\n🎉 Daily Team Report generation completed!')
        print('📧 Check your email for team reports!')
        "
