name: Paul TODO Summary - Consolidated Email

on:
  schedule:
    # Run every day at 7 AM UTC (after team reports)
    - cron: '0 7 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  paul-todo-summary:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate Paul TODO Summary
      env:
        SLACK_XOXC_TOKEN: ${{ secrets.SLACK_XOXC_TOKEN }}
        SLACK_XOXD_TOKEN: ${{ secrets.SLACK_XOXD_TOKEN }}
        JIRA_URL: ${{ secrets.JIRA_URL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_TOKEN }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      run: |
        python .github/workflows/scripts/paul_todo_summary.py

